# Generated by Django 3.2.4 on 2021-08-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MMDList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('song_title', models.CharField(max_length=256)),
                ('song_composer', models.CharField(max_length=128)),
                ('character', models.CharField(max_length=256)),
                ('creator', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=512)),
                ('saved_url', models.CharField(max_length=512, null=True)),
            ],
        ),
    ]
