# Generated by Django 3.2.4 on 2021-08-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmd', '0002_mmdlist_lyrics_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMDCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('name_original', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MMDMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MMDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='VocaloidSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('composer', models.CharField(max_length=128)),
                ('lyrics_url', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MMDMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=512)),
                ('saved_url', models.CharField(max_length=512, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmd.mmdcharacter')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmd.mmdmaker')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmd.mmdmodel')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmd.vocaloidsong')),
            ],
        ),
    ]
