# Generated by Django 3.2.4 on 2021-08-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmd', '0004_mmdcharacter_name_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmdmovie',
            name='url_type',
            field=models.CharField(default='youtube', max_length=16),
        ),
    ]
