# Generated by Django 3.2.4 on 2021-10-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(default=0)),
                ('parent', models.BigIntegerField(null=True)),
                ('code', models.CharField(default='000', max_length=3)),
                ('name', models.CharField(default='', max_length=32)),
                ('order', models.IntegerField(default=999)),
                ('begin_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('is_slip', models.BooleanField(default=False)),
                ('is_temporary', models.BooleanField(default=False)),
                ('bank_type', models.CharField(default='00', max_length=2)),
                ('deposit_type', models.CharField(default='00', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('desc', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SlipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('is_debit', models.BooleanField(default=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accbook.accounts')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accbook.slip')),
            ],
        ),
    ]
