# Generated by Django 3.2.4 on 2021-10-29 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='code',
        ),
    ]
