# Generated by Django 3.2.4 on 2021-10-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='code1',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='code2',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='code3',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='order1',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='order2',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='order3',
            field=models.IntegerField(default=999),
        ),
    ]
