# Generated by Django 3.2.4 on 2021-10-29 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accbook', '0002_remove_accounts_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FnInst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('type', models.IntegerField(default=999)),
                ('order', models.IntegerField(default=999)),
            ],
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='bank_type',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='deposit_type',
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('deposit_type', models.IntegerField(default=999)),
                ('is_protected', models.BooleanField(default=False)),
                ('state', models.CharField(default='정상', max_length=32)),
                ('interest_rate', models.CharField(default='', max_length=32)),
                ('begin_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('description', models.CharField(default='', max_length=1024)),
                ('order', models.IntegerField(default=999)),
                ('fn_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accbook.fninst')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accbook.deposit'),
        ),
    ]
