# Generated by Django 3.2.4 on 2021-10-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accbook', '0002_auto_20211002_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='name1',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='name2',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='name3',
            field=models.CharField(default='', max_length=32),
        ),
    ]
