# Generated by Django 3.2.4 on 2021-10-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accbook', '0004_deposit_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='deposit_type',
            new_name='type',
        ),
    ]
