# Generated by Django 3.2.4 on 2021-10-31 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accbook', '0005_rename_deposit_type_deposit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='deposit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accbook.deposit'),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('number', models.CharField(default='', max_length=32)),
                ('type', models.IntegerField(default=999)),
                ('intn_type', models.IntegerField(default=999)),
                ('state', models.CharField(default='정상', max_length=32)),
                ('is_trans', models.BooleanField(default=False)),
                ('is_cash', models.BooleanField(default=False)),
                ('fee', models.IntegerField(default=0)),
                ('interest_rate', models.CharField(default='', max_length=32)),
                ('begin_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('valid_date', models.DateField(null=True)),
                ('description', models.CharField(default='', max_length=1024)),
                ('order', models.IntegerField(default=999)),
                ('deposit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accbook.deposit')),
                ('fn_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accbook.fninst')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accbook.creditcard'),
        ),
    ]
