# Generated by Django 3.2.4 on 2021-11-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accbook', '0007_remove_creditcard_interest_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slipdata',
            old_name='code',
            new_name='account',
        ),
        migrations.AddField(
            model_name='slip',
            name='target',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='slip',
            name='desc',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='slipdata',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
