# Generated by Django 3.2.4 on 2021-11-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accbook', '0008_auto_20211101_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_both',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_debit',
            field=models.BooleanField(default=False),
        ),
    ]
