# Generated by Django 3.2.4 on 2021-11-05 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accbook', '0010_slip_is_temporary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000)),
                ('month', models.IntegerField(default=1)),
                ('update_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AnnualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accbook.accounts')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accbook.annual')),
            ],
        ),
    ]
