# Generated by Django 3.2.4 on 2021-11-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accbook', '0011_annual_annualdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annual',
            new_name='Monthly',
        ),
        migrations.RenameModel(
            old_name='AnnualData',
            new_name='MonthlyData',
        ),
    ]
