# Generated by Django 3.2.4 on 2021-12-05 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accbook', '0014_accounts_is_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FnProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('code', models.CharField(default='', max_length=32)),
                ('is_domestic', models.BooleanField(default=False)),
                ('type', models.IntegerField(default=999)),
                ('description', models.CharField(default='', max_length=1024)),
                ('order', models.IntegerField(default=999)),
                ('price', models.IntegerField(default=0)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accbook.deposit')),
            ],
        ),
    ]
