# Generated by Django 3.2.4 on 2021-12-05 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accbook', '0017_alter_fnprod_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FnTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('buy_price', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('fn_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accbook.fnprod')),
            ],
        ),
    ]
