# Generated by Django 3.2.4 on 2021-12-08 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accbook', '0020_fnprod_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fntrade',
            name='sell_date',
        ),
        migrations.RemoveField(
            model_name='fntrade',
            name='sell_price',
        ),
        migrations.CreateModel(
            name='FnTradeSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateTimeField()),
                ('buy_price', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('sell_date', models.DateTimeField(null=True)),
                ('sell_price', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('fn_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accbook.fnprod')),
            ],
        ),
    ]
