# Generated by Django 3.2.4 on 2021-12-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accbook', '0021_auto_20211208_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccBookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_usd', models.DecimalField(decimal_places=4, default=1000, max_digits=10)),
                ('rate_usd_default', models.DecimalField(decimal_places=4, default=1000, max_digits=10)),
            ],
        ),
    ]
