# Generated by Django 3.2.4 on 2021-06-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='json_file',
            field=models.CharField(default='test.json', max_length=32),
            preserve_default=False,
        ),
    ]
