# Generated by Django 3.2.4 on 2021-06-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_listitem_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='memo',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
