# Generated by Django 3.2.4 on 2021-06-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_listitem_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='listitem',
            name='price',
        ),
    ]
