# Generated by Django 3.2.4 on 2021-06-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_remove_listitem_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='last_update_day',
            field=models.CharField(default='', max_length=16),
        ),
    ]
