# Generated by Django 3.2.4 on 2021-06-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_auto_20210630_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_no', models.CharField(max_length=16, unique=True)),
                ('article_confirm_ymd', models.CharField(max_length=16)),
                ('is_new', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('memo', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
    ]
