# Generated by Django 3.2.4 on 2021-09-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_locationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylanditem',
            name='parent_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
