# Generated by Django 3.2.4 on 2021-09-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_mylanditem_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylanditem',
            name='initial_price',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
