# Generated by Django 3.2.4 on 2021-10-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0012_mylanditem_initial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylanditem',
            name='declared_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mylanditem',
            name='declared_value_date',
            field=models.DateField(null=True),
        ),
    ]
