# Generated by Django 3.2.4 on 2021-10-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_auto_20211005_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realestate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_jibun', models.CharField(max_length=64)),
                ('address_road', models.CharField(max_length=64)),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('building_area', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_floor_area', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('use_approval_date', models.DateField(null=True)),
                ('structure', models.CharField(max_length=16, null=True)),
                ('heating', models.CharField(max_length=16, null=True)),
                ('sewage', models.CharField(max_length=32, null=True)),
                ('declared_value', models.IntegerField(null=True)),
                ('declared_value_date', models.DateField(null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('memo', models.CharField(default='', max_length=1024)),
                ('photo_prefix', models.CharField(max_length=32, null=True)),
                ('building_master_prefix', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mylanditem',
            name='realestate_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
