# Generated by Django 3.2.4 on 2021-10-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0014_auto_20211005_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylanditem',
            name='price',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
