# Generated by Django 3.2.4 on 2021-10-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0015_mylanditem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylanditem',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
