# Generated by Django 3.2.4 on 2021-10-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0016_alter_mylanditem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='address_road',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
