# Generated by Django 3.2.4 on 2021-10-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0017_alter_realestate_address_road'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='building_master_prefix',
            new_name='file_prefix',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='photo_prefix',
        ),
    ]
