# Generated by Django 3.2.4 on 2021-10-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0018_auto_20211006_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='is_dandok',
            field=models.BooleanField(default=False),
        ),
    ]
