# Generated by Django 3.2.4 on 2021-10-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0019_realestate_is_dandok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='address_road',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='declared_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='file_prefix',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='heating',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='sewage',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='structure',
            field=models.CharField(default='', max_length=16),
        ),
    ]
