# Generated by Django 3.2.4 on 2021-10-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0020_auto_20211007_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylanditem',
            name='initial_price',
        ),
        migrations.RemoveField(
            model_name='mylanditem',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='mylanditem',
            name='is_multi_family',
        ),
        migrations.RemoveField(
            model_name='mylanditem',
            name='memo',
        ),
    ]
