# Generated by Django 3.2.4 on 2021-10-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0021_auto_20211007_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='deal_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='deal_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='lawd_cd',
            field=models.CharField(default='', max_length=10),
        ),
    ]
