# Generated by Django 3.2.4 on 2021-10-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0022_auto_20211008_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawd_cd', models.CharField(default='', max_length=10)),
                ('sido', models.CharField(default='', max_length=16)),
                ('sigungu', models.CharField(default='', max_length=16)),
                ('eupmyun', models.CharField(default='', max_length=16)),
                ('ri', models.CharField(default='', max_length=16)),
                ('is_san', models.IntegerField(default=0)),
                ('jibun_bonbun', models.IntegerField(null=True)),
                ('jibun_bubun', models.IntegerField(null=True)),
                ('road_cd', models.CharField(default='', max_length=12)),
                ('road', models.CharField(default='', max_length=16)),
                ('road_bonbun', models.IntegerField(null=True)),
                ('road_bubun', models.IntegerField(null=True)),
                ('house_cd', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
