# Generated by Django 3.2.4 on 2021-10-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0023_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='jibun_bonbun',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='address',
            name='jibun_bubun',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='address',
            name='road_bonbun',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='address',
            name='road_bubun',
            field=models.IntegerField(default=0),
        ),
    ]
